### ISSUE TITLE
Magento demo?

### ISSUE THREAD

**Issue by cybercamphackathon** [onticsoluciones/nofraud#3]
Do not commit binary files, logs, caches or other trash in git

**Comment by alfonsomoratalla** [comment]
Magento demo directory cleaned in 4ee0d4141cbd079b8c57e15efbc269d4f98a5eae

@alsanchez  Should we rewrite history?

**Comment by alsanchez** [comment]
Yep, just used the BFG Repo-Cleaner to remove the big blobs that were bloating the repository. We still need to include a proper .gitignore for the Magento subdirectory.

**Comment by alsanchez** [comment]
.gitignore added, so I guess this can be closed.

**Comment by cybercamphackathon** [comment]
magento-demo is still 141MB, reopen this issue because it is not solved

**Comment by alsanchez** [comment]
We need to move all external files to https://github.com/onticsoluciones/nofraud-sample-data

**Comment by alfonsomoratalla** [comment]
Solved in 80b391114750b29d0b23b271f9c93881092fcf28
